### ISSUE TITLE
Requesting attachment of documents

### ISSUE THREAD

**Issue by VijayVm1701** [VijayVm17/WhatsUp_Development#4]
Dear VijayVm17,
          It would be great if the app has the feature to attach and upload the documents as well , Kindly add this feature

**Comment by VijayVm17** [comment]
Dear VijayVm1701 ,
           Thanks For suggesting this feature, We will update and let you  Know

**Comment by VijayVm17** [comment]
Dear VijayVm1701,
          Thanks for Your valuable suggestions , This feature is going to make our product great
